require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/api/v1/periodes', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Periode. As you add validations to Periode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    lembaga = create(:lembaga)
    {
      tahun_awal: 2025,
      tahun_akhir: 2030,
      lembaga_id: lembaga.id
    }
  end

  let(:invalid_attributes) do
    lembaga = create(:lembaga)
    {
      tahun_awal: 2020,
      tahun_akhir: 2010,
      lembaga_id: lembaga.id
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # PeriodesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    user = create(:user)
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Periode.create! valid_attributes
      get api_v1_periodes_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      periode = Periode.create! valid_attributes
      get api_v1_periode_url(periode), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Periode' do
        expect do
          post api_v1_periodes_url,
               params: { periode: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Periode, :count).by(1)
      end

      it 'renders a JSON response with the new periode' do
        post api_v1_periodes_url,
             params: { periode: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Periode' do
        expect do
          post api_v1_periodes_url,
               params: { periode: invalid_attributes }, as: :json
        end.to change(Periode, :count).by(0)
      end

      it 'renders a JSON response with errors for the new periode' do
        post api_v1_periodes_url,
             params: { periode: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          tahun_awal: 2025,
          tahun_akhir: 2035
        }
      end

      it 'updates the requested periode' do
        periode = Periode.create! valid_attributes
        patch api_v1_periode_url(periode),
              params: { periode: new_attributes }, headers: valid_headers, as: :json
        periode.reload
        expect(periode).to be_valid
        update_response = JSON.parse(response.body).deep_symbolize_keys
        expect(update_response[:nama_periode]).to eq('Periode 2025-2035')
      end

      it 'renders a JSON response with the periode' do
        periode = Periode.create! valid_attributes
        patch api_v1_periode_url(periode),
              params: { periode: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the periode' do
        periode = Periode.create! valid_attributes
        patch api_v1_periode_url(periode),
              params: { periode: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested periode' do
      periode = Periode.create! valid_attributes
      expect do
        delete api_v1_periode_url(periode), headers: valid_headers, as: :json
      end.to change(Periode, :count).by(-1)
    end
  end
end
