require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/api/v1/urusans', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Urusan. As you add validations to Urusan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      urusan: 'Urusan a',
      kode_urusan: '1'
    }
  end

  let(:invalid_attributes) do
    {
      urusan: '',
      kode_urusan: ''
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UrusansController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    user = create(:user)
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Urusan.create! valid_attributes
      get api_v1_urusans_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      urusan = Urusan.create! valid_attributes
      get api_v1_urusan_url(urusan), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Urusan' do
        expect do
          post api_v1_urusans_url,
               params: { urusan: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Urusan, :count).by(1)
      end

      it 'renders a JSON response with the new urusan' do
        post api_v1_urusans_url,
             params: { urusan: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Urusan' do
        expect do
          post api_v1_urusans_url,
               params: { urusan: invalid_attributes }, as: :json
        end.to change(Urusan, :count).by(0)
      end

      it 'renders a JSON response with errors for the new urusan' do
        post api_v1_urusans_url,
             params: { urusan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          urusan: 'new urusan'
        }
      end

      it 'updates the requested urusan' do
        urusan = Urusan.create! valid_attributes
        patch api_v1_urusan_url(urusan),
              params: { urusan: new_attributes }, headers: valid_headers, as: :json
        urusan.reload
        update_res = JSON.parse(response.body).deep_symbolize_keys
        expect(urusan.urusan).to eq('new urusan')
        expect(update_res[:urusan]).to eq('new urusan')
      end

      it 'renders a JSON response with the urusan' do
        urusan = Urusan.create! valid_attributes
        patch api_v1_urusan_url(urusan),
              params: { urusan: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the urusan' do
        urusan = Urusan.create! valid_attributes
        patch api_v1_urusan_url(urusan),
              params: { urusan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested urusan' do
      urusan = Urusan.create! valid_attributes
      expect do
        delete api_v1_urusan_url(urusan), headers: valid_headers, as: :json
      end.to change(Urusan, :count).by(-1)
    end
  end
end
