require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bidang_urusans', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # BidangUrusan. As you add validations to BidangUrusan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      bidang_urusan: 'Test Bidang Urusan',
      kode_bidang_urusan: '1.05'
    }
  end

  let(:invalid_attributes) do
    {
      bidang_urusan: ''
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # BidangUrusansController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    user = create(:user)
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BidangUrusan.create! valid_attributes
      get bidang_urusans_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bidang_urusan = BidangUrusan.create! valid_attributes
      get bidang_urusan_url(bidang_urusan), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BidangUrusan' do
        expect do
          post bidang_urusans_url,
               params: { bidang_urusan: valid_attributes }, headers: valid_headers, as: :json
        end.to change(BidangUrusan, :count).by(1)
      end

      it 'renders a JSON response with the new bidang_urusan' do
        post bidang_urusans_url,
             params: { bidang_urusan: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BidangUrusan' do
        expect do
          post bidang_urusans_url,
               params: { bidang_urusan: invalid_attributes }, as: :json
        end.to change(BidangUrusan, :count).by(0)
      end

      it 'renders a JSON response with errors for the new bidang_urusan' do
        post bidang_urusans_url,
             params: { bidang_urusan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          bidang_urusan: 'new bidang urusan'
        }
      end

      it 'updates the requested bidang_urusan' do
        bidang_urusan = BidangUrusan.create! valid_attributes
        patch bidang_urusan_url(bidang_urusan),
              params: { bidang_urusan: new_attributes }, headers: valid_headers, as: :json
        bidang_urusan.reload
        update_res = JSON.parse(response.body).deep_symbolize_keys
        expect(bidang_urusan.bidang_urusan).to eq('new bidang urusan')
        expect(update_res[:bidang_urusan]).to eq('new bidang urusan')
      end

      it 'renders a JSON response with the bidang_urusan' do
        bidang_urusan = BidangUrusan.create! valid_attributes
        patch bidang_urusan_url(bidang_urusan),
              params: { bidang_urusan: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the bidang_urusan' do
        bidang_urusan = BidangUrusan.create! valid_attributes
        patch bidang_urusan_url(bidang_urusan),
              params: { bidang_urusan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bidang_urusan' do
      bidang_urusan = BidangUrusan.create! valid_attributes
      expect do
        delete bidang_urusan_url(bidang_urusan), headers: valid_headers, as: :json
      end.to change(BidangUrusan, :count).by(-1)
    end
  end
end
