require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/indikators', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Indikator. As you add validations to Indikator, be sure to
  # adjust the attributes here as well.
  let(:opd) { create(:opd) }
  let(:tujuan) { create(:tujuan, tujuanable_type: 'Opd', tujuanable_id: opd.id) }
  let(:valid_attributes) do
    {
      indikator: 'Test indikator',
      indikatorable_type: 'Tujuan',
      indikatorable_id: tujuan.id
    }
  end

  let(:invalid_attributes) do
    {
      indikator: '',
      indikatorable_type: 'Tujuan',
      indikatorable_id: tujuan.id
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # IndikatorsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    user = create(:user)
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Indikator.create! valid_attributes
      get indikators_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      indikator = Indikator.create! valid_attributes
      get indikator_url(indikator), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Indikator' do
        expect do
          post indikators_url,
               params: { indikator: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Indikator, :count).by(1)
      end

      it 'renders a JSON response with the new indikator' do
        post indikators_url,
             params: { indikator: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Indikator' do
        expect do
          post indikators_url,
               params: { indikator: invalid_attributes }, as: :json
        end.to change(Indikator, :count).by(0)
      end

      it 'renders a JSON response with errors for the new indikator' do
        post indikators_url,
             params: { indikator: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          indikator: 'Update A'
        }
      end

      it 'updates the requested indikator' do
        indikator = Indikator.create! valid_attributes
        patch indikator_url(indikator),
              params: { indikator: new_attributes }, headers: valid_headers, as: :json
        indikator.reload
        update_res = JSON.parse(response.body).deep_symbolize_keys
        expect(indikator.indikator).to eq('Update A')
        expect(update_res[:indikator]).to eq('Update A')
      end

      it 'renders a JSON response with the indikator' do
        indikator = Indikator.create! valid_attributes
        patch indikator_url(indikator),
              params: { indikator: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the indikator' do
        indikator = Indikator.create! valid_attributes
        patch indikator_url(indikator),
              params: { indikator: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested indikator' do
      indikator = Indikator.create! valid_attributes
      expect do
        delete indikator_url(indikator), headers: valid_headers, as: :json
      end.to change(Indikator, :count).by(-1)
    end
  end
end
