require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/kegiatans', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Kegiatan. As you add validations to Kegiatan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      kegiatan: 'Kegiatan A',
      kode_kegiatan: '1.01.03.2.01'
    }
  end

  let(:invalid_attributes) do
    {
      kegiatan: '',
      kode_kegiatan: ''
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # KegiatansController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    user = create(:user)
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Kegiatan.create! valid_attributes
      get kegiatans_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      kegiatan = Kegiatan.create! valid_attributes
      get kegiatan_url(kegiatan), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Kegiatan' do
        expect do
          post kegiatans_url,
               params: { kegiatan: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Kegiatan, :count).by(1)
      end

      it 'renders a JSON response with the new kegiatan' do
        post kegiatans_url,
             params: { kegiatan: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Kegiatan' do
        expect do
          post kegiatans_url,
               params: { kegiatan: invalid_attributes }, as: :json
        end.to change(Kegiatan, :count).by(0)
      end

      it 'renders a JSON response with errors for the new kegiatan' do
        post kegiatans_url,
             params: { kegiatan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          kegiatan: 'new kegiatan'
        }
      end

      it 'updates the requested kegiatan' do
        kegiatan = Kegiatan.create! valid_attributes
        patch kegiatan_url(kegiatan),
              params: { kegiatan: new_attributes }, headers: valid_headers, as: :json
        kegiatan.reload
        update_res = JSON.parse(response.body).deep_symbolize_keys
        expect(kegiatan.kegiatan).to eq('new kegiatan')
        expect(update_res[:kegiatan]).to eq('new kegiatan')
      end

      it 'renders a JSON response with the kegiatan' do
        kegiatan = Kegiatan.create! valid_attributes
        patch kegiatan_url(kegiatan),
              params: { kegiatan: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the kegiatan' do
        kegiatan = Kegiatan.create! valid_attributes
        patch kegiatan_url(kegiatan),
              params: { kegiatan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested kegiatan' do
      kegiatan = Kegiatan.create! valid_attributes
      expect do
        delete kegiatan_url(kegiatan), headers: valid_headers, as: :json
      end.to change(Kegiatan, :count).by(-1)
    end
  end
end
