require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/subkegiatans', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Subkegiatan. As you add validations to Subkegiatan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      subkegiatan: 'Subkegiatan A',
      kode_subkegiatan: '5.01.03.2.01.0005'
    }
  end

  let(:invalid_attributes) do
    {
      subkegiatan: '',
      kode_subkegiatan: ''
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SubkegiatansController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Subkegiatan.create! valid_attributes
      get subkegiatans_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      subkegiatan = Subkegiatan.create! valid_attributes
      get subkegiatan_url(subkegiatan), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Subkegiatan' do
        expect do
          post subkegiatans_url,
               params: { subkegiatan: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Subkegiatan, :count).by(1)
      end

      it 'renders a JSON response with the new subkegiatan' do
        post subkegiatans_url,
             params: { subkegiatan: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Subkegiatan' do
        expect do
          post subkegiatans_url,
               params: { subkegiatan: invalid_attributes }, as: :json
        end.to change(Subkegiatan, :count).by(0)
      end

      it 'renders a JSON response with errors for the new subkegiatan' do
        post subkegiatans_url,
             params: { subkegiatan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          subkegiatan: 'new subkegiatan'
        }
      end

      it 'updates the requested subkegiatan' do
        subkegiatan = Subkegiatan.create! valid_attributes
        patch subkegiatan_url(subkegiatan),
              params: { subkegiatan: new_attributes }, headers: valid_headers, as: :json
        subkegiatan.reload
        update_res = JSON.parse(response.body).deep_symbolize_keys
        expect(subkegiatan.subkegiatan).to eq('new subkegiatan')
        expect(update_res[:subkegiatan]).to eq('new subkegiatan')
      end

      it 'renders a JSON response with the subkegiatan' do
        subkegiatan = Subkegiatan.create! valid_attributes
        patch subkegiatan_url(subkegiatan),
              params: { subkegiatan: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the subkegiatan' do
        subkegiatan = Subkegiatan.create! valid_attributes
        patch subkegiatan_url(subkegiatan),
              params: { subkegiatan: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested subkegiatan' do
      subkegiatan = Subkegiatan.create! valid_attributes
      expect do
        delete subkegiatan_url(subkegiatan), headers: valid_headers, as: :json
      end.to change(Subkegiatan, :count).by(-1)
    end
  end
end
