---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/opds":
    get:
      summary: list opds
      responses:
        '200':
          description: successful
    post:
      summary: create opd
      responses:
        '200':
          description: successful
  "/api/v1/opds/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show opd
      responses:
        '200':
          description: successful
    patch:
      summary: update opd
      responses:
        '200':
          description: successful
    put:
      summary: update opd
      responses:
        '200':
          description: successful
    delete:
      summary: delete opd
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
